using System.Text;
using OpenDesignCore.Provenance;
using Xunit;

namespace OpenDesignCore.Tests;

/// <summary>
/// Byte-parity with Project BINGO's canonical_json (v3/bingo/models.py).
/// Expected bytes and hashes below were generated by running the actual
/// Python kernel function on 2026-08-15 — not hand-derived.
/// </summary>
public sealed class CanonicalJsonTests
{
    [Fact]
    public void SortsKeysAndOmitsWhitespace()
    {
        Dictionary<string, object?> oValue = new() { ["b"] = 1, ["a"] = "x" };

        Assert.Equal("""{"a":"x","b":1}""", Encoding.ASCII.GetString(CanonicalJson.Serialize(oValue)));
        Assert.Equal(
            "cdab067e9f3beb32d1252cfd63e492592fecbf591b0d08cadb24bb17f3864246",
            CanonicalJson.StrSha256(oValue));
    }

    [Fact]
    public void EscapesNonAsciiLikePythonEnsureAscii()
    {
        Dictionary<string, object?> oValue = new()
        {
            ["name"] = "héllo ☃",
            ["n"] = new List<object?>
            {
                1, 2, new Dictionary<string, object?> { ["k"] = null, ["t"] = true },
            },
        };

        // Expected bytes are pure ASCII with Python-style ensure_ascii escapes
        // (backslash-u sequences), so the literal is built with escaped backslashes.
        string strExpected =
            "{\"n\":[1,2,{\"k\":null,\"t\":true}],\"name\":\"h\\u00e9llo \\u2603\"}";
        Assert.Equal(strExpected, Encoding.ASCII.GetString(CanonicalJson.Serialize(oValue)));
        Assert.Equal(
            "c86c2b11f1ca902f108921b4106de227b3b914b05a69ee474b9c7e718bdb7129",
            CanonicalJson.StrSha256(oValue));
    }

    [Fact]
    public void ProvenanceShapedValue_MatchesPythonHash()
    {
        Dictionary<string, object?> oValue = new()
        {
            ["schema"] = "odc/provenance/0.1",
            ["voxel_size_mm"] = "0.20",
            ["inputs"] = new Dictionary<string, object?>
            {
                ["part_id"] = "parts/esp32-s3-wroom-1",
                ["wall_mm"] = "2.40",
                ["clearance_mm"] = "0.30",
            },
        };

        Assert.Equal(
            "949c4ce2e41ca48ea9ea36550d2550f19d87aef9aeacab66ea5c51237bdbfb11",
            CanonicalJson.StrSha256(oValue));
    }

    [Fact]
    public void FloatingPoint_IsRejected()
    {
        Dictionary<string, object?> oValue = new() { ["v"] = 0.2 };
        Assert.Throws<ArgumentException>(() => CanonicalJson.Serialize(oValue));
    }
}
